# -*- coding: utf-8 -*-
"""abalone.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xXvfhnKSPxOSMtbkBsipgEZri1DWV3Fe

###TASK 1

Importing required libraries
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""Loading dataset"""

from google.colab import files
uploaded=files.upload()

df=pd.read_csv("abalone_data.csv")
df.head()

columns=["sex","length","diameter","height","whole_weight","shucked_weight","rings"]
df=pd.read_csv("abalone_data.csv",header=None,names=columns)
df.head()

df.shape

df.info()

"""##Displaying dataset information
First 10 records
"""

print(df.head(10))

"""dataset shape"""

print("Dataset shape:",df.shape)

"""checking for missing and duplicate values"""

print("missing values:\n",df.isnull().sum())
print("duplicate records:",df.duplicated().sum())

"""###TASK 2

"""

#converting categorical data
df_encoded=pd.get_dummies(df, columns=["sex"], drop_first=True)

#define features and target
X=df_encoded.drop("rings",axis=1)
y=df_encoded["rings"]+1.5

#train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

#train linear regression model
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

#predict age on test data
y_pred = model.predict(X_test)

"""###TASK 3"""

#performance metrics
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2  = r2_score(y_test, y_pred)

print("Mean Absolute Error (MAE):", mae)
print("Mean Squared Error (MSE):", mse)
print("R2 Score:", r2)